### ISSUE TITLE
offical doc and usage seciton

### ISSUE THREAD

**Issue by peter279k** [odan/image#3]
As title, it has the two works should do.

- Official doc. How about use the [phpDocumentor](https://phpdoc.org)?
- usage section in ```README.md```.

If having the available time, I can be responsible for this.

Thanks.

**Comment by odan** [comment]
It would be nice to have "Requirements", "Installation" and "Usage" section in the  `README.md` file.
I would like to see the documentation in a subfolder `docs/` with the all the *.md files. I assign you for this issue.

**Comment by odan** [comment]
Cool, thanks!

**Comment by odan** [comment]
PS: An `docs/README.md` as "index" would be nice.

**Comment by peter279k** [comment]
Ok, I just create other PR to add the new ```README.md``` in ```docs``` folder.
Please feel free to send the comments :).

Thanks.
