### ISSUE TITLE
Detecting Imgae type needs to be enhanced

### ISSUE THREAD

**Issue by peter279k** [odan/image#7]
As title. Consider the following scenario:
The ```png``` file content, but its name is the ```png_content.jpg```.
And using the ```convertImage``` will detect this file incorrectly.
It will detect a ```jpg``` file because of the file extension.

To solve the issue, it should use the [getimagesize ](http://php.net/manual/en/function.getimagesize.php)or [exif_imagetype ](http://php.net/manual/en/function.exif-imagetype.php)function.

What do you think?
Thanks.

**Comment by odan** [comment]
I think this is a good idea. 

The only problem is that exif_imagetype requires the exif php extension. Maybe we could check if the function exists.

Can you create a PR?

**Comment by peter279k** [comment]
Sure! I will do this.

2018年3月9日 下午7:00，"Daniel Opitz" <notifications@github.com>寫道：

**Comment by peter279k** [comment]
I think this problem will not happen because the ```$fileName``` is the destination file name :-).
